# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-08-11 02:32
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': '\u7c7b\u522b'},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'verbose_name_plural': '\u5e16\u5b50'},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'verbose_name_plural': '\u6807\u7b7e'},
        ),
        migrations.AlterField(
            model_name='category',
            name='cname',
            field=models.CharField(max_length=30, unique=True, verbose_name='\u7c7b\u522b\u540d\u79f0'),
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tag',
            name='tname',
            field=models.CharField(max_length=30, unique=True, verbose_name='\u6807\u7b7e\u540d\u79f0'),
        ),
    ]
